apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Object
    object:
      metric:
        name: request_per_second
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: frontend
      target:
        type: Value
        value: 30
